apiVersion: apps/v1
kind: Deployment
metadata:
  name: cats-dogs-api
  labels:
    app: cats-dogs-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cats-dogs-api
  template:
    metadata:
      labels:
        app: heart-disease-api
    spec:
      containers:
      - name: api
        image: cats-dogs-api:local
        imagePullPolicy: IfNotPresent  # Crucial for local Docker Desktop usage
        ports:
        - containerPort: 8000
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: cats-dogs-api-service
spec:
  type: LoadBalancer
  selector:
    app: cats-dogs-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000